### ISSUE TITLE
Pre-trained Inception model for FID computation

### ISSUE THREAD

**Issue by ankanbhunia** [facebookresearch/DoodlerGAN#6]
I believe that the FID score reported in the paper is computed using an Inception model that is pre-trained on QuickDraw3.8M dataset. Could you please share the pre-trained model used for the FID calculation?

**Comment by songweige** [comment]
Thanks for your interests in our paper. We have updated the pretrained inception model in the shared model.zip file. Please find it at https://drive.google.com/drive/u/4/folders/14ZywlSE-khagmSz23KKFbLCQLoMOxPzl.
